### ISSUE TITLE
Changes Chapter 2

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/ds#7]
- [x] Video introduction to RStudio (+add a small intro to the video)
- [x] Video to illustrate `cache = TRUE` (+add a small intro to the video)
- [x] Also I would remove the section "Shiny App" and just leave the text, the video and the app in the introduction
- [x] Link to shiny app (regular)
- [x] Add command to run apps locally

**Comment by Shwizzy** [comment]
Link to RMarkdown Cheatsheet. Found under 2.4.1 & 2.6. 

https://www.rstudio.com/wp-content/uploads/2015/02/RMarkdown-cheatsheet.pdf
